name: hrm
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.0.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  mime: ^2.0.0
  http_parser: 4.0.2
  shared_preferences: ^2.0.13
  camera: ^0.11.0+2
  intl: ^0.19.0
  provider: ^6.1.2
  device_info_plus: ^11.2.0
  google_maps_flutter: ^2.1.1
  open_file: ^3.2.1
  path_provider: ^2.0.11
  flutter_launcher_icons: ^0.14.2
  package_info_plus: ^8.1.2
  cached_network_image: ^3.2.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  android_icon_size: 512
 

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
    
    
flutter:
  uses-material-design: true
  assets:
    - assets/images/
